### ISSUE TITLE
LR_s are not correct for Solisense LRC. 

### ISSUE THREAD

**Issue by mireillesavoie** [FundyPhytoPhys/FluorO2Calibrations#3]
The LR_s in O2 data do not line up with LR_s in solisense data because upon LRC protocol start no induction/relaxation LRC is measured until  180 seconds later. After 180 sec the first measurement is ActPar = 0.

So ~180 sec needs to be added to LR_s in the 'SolisenseImportMiSa.Rmd' and 'SolisenseImportSySl.Rmd' (also MaBe import .rmd)
in chunk labeled 'durations' around line 230.

I did not do this. Want to consult Doug.

**Comment by GitHubDoug** [comment]
We can discuss, it might or might not be OK with the interpolation of the ActPARCorr etc. from the SoliSense data files.

**Comment by mireillesavoie** [comment]
No problem FRR and O2 LR_s match with proper slopes calculated
